import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import Header from './Header';
import Footer from './Footer';
import styles from './GlossaryPage.module.css';

const GLOSSARY_TERMS = [
    {
        term: 'AI Talent Passport',
        definition: 'A verified, portable credential issued by Froscel that captures a candidate\'s skills, coding proficiency, behavioral traits, and interview performance into a single tamper-proof digital passport.',
    },
    {
        term: 'Adaptive AI Interview',
        definition: 'An interview where questions dynamically adjust in real-time based on the candidate\'s responses, skill level, and performance, ensuring a fair and personalized assessment experience.',
    },
    {
        term: 'SFU (Selective Forwarding Unit)',
        definition: 'A server architecture used in WebRTC video calls that receives media streams from each participant and selectively forwards them to others, enabling efficient multi-party video interviews.',
    },
    {
        term: 'Proctoring',
        definition: 'Real-time integrity monitoring during assessments that uses AI to detect face presence, multiple people, tab switching, and other violations to ensure fair evaluation conditions.',
    },
    {
        term: 'Live Code Evaluation',
        definition: 'An in-browser coding environment (powered by Monaco Editor) that allows candidates to write, compile, and execute code in 9+ programming languages during interviews, with real-time output visible to interviewers.',
    },
    {
        term: 'WebRTC',
        definition: 'Web Real-Time Communication — a technology that enables peer-to-peer audio, video, and data sharing directly in the browser without plugins, used by Froscel Interview Room for secure video interviews.',
    },
    {
        term: 'Bias-Free Assessment',
        definition: 'An evaluation methodology that uses standardized, AI-generated questions and objective scoring criteria to minimize unconscious human bias in hiring decisions.',
    },
    {
        term: 'Behavioral Telemetry',
        definition: 'The collection and analysis of candidate behavioral signals during interviews, such as response time, confidence patterns, and engagement levels, to provide deeper insights beyond raw answers.',
    },
    {
        term: 'Hiring Pipeline',
        definition: 'A structured workflow that tracks candidates through each stage of the recruitment process — from application and screening, through interviews and evaluation, to offer and onboarding.',
    },
    {
        term: 'Integrity Score',
        definition: 'A numerical rating generated by Froscel\'s proctoring system that reflects the level of compliance and fair behavior exhibited by a candidate during an assessment.',
    },
    {
        term: 'AI Co-Interviewer',
        definition: 'An AI agent that participates alongside human interviewers, generating contextual follow-up questions, providing real-time candidate scoring, and producing post-interview intelligence reports.',
    },
    {
        term: 'Programmatic Hiring',
        definition: 'The use of automated, data-driven systems to manage recruitment at scale, including job distribution, candidate scoring, and pipeline management through AI and machine learning.',
    },
];

const GlossaryPage = () => {
    // Scroll to top on mount
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    // Force light theme
    useEffect(() => {
        const previousTheme = document.documentElement.getAttribute('data-theme');
        document.documentElement.setAttribute('data-theme', 'light');
        return () => {
            if (previousTheme) document.documentElement.setAttribute('data-theme', previousTheme);
        };
    }, []);

    return (
        <div className={styles.page}>
            <Header />
            <main>
                <section className={styles.hero}>
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                    >
                        <Link to="/" className={styles.backLink}>← Back to Home</Link>
                        <h1 className={styles.title}>
                            Hiring & AI <br />
                            <span className={styles.gradient}>Interview Glossary</span>
                        </h1>
                        <p className={styles.subtitle}>
                            Definitions for key terms in AI-powered hiring, technical interviews, and recruitment technology.
                        </p>
                    </motion.div>
                </section>

                <section className={styles.glossary}>
                    <div className={styles.termList}>
                        {GLOSSARY_TERMS.sort((a, b) => a.term.localeCompare(b.term)).map((item, index) => (
                            <motion.article
                                key={item.term}
                                className={styles.termCard}
                                id={item.term.toLowerCase().replace(/\s+/g, '-')}
                                initial={{ opacity: 0, y: 20 }}
                                whileInView={{ opacity: 1, y: 0 }}
                                viewport={{ once: true }}
                                transition={{ delay: index * 0.05 }}
                            >
                                <h2 className={styles.termTitle}>{item.term}</h2>
                                <p className={styles.termDef}>{item.definition}</p>
                            </motion.article>
                        ))}
                    </div>
                </section>

                <section className={styles.ctaSection}>
                    <motion.div
                        initial={{ opacity: 0, scale: 0.95 }}
                        whileInView={{ opacity: 1, scale: 1 }}
                        viewport={{ once: true }}
                    >
                        <h2>Ready to transform your hiring?</h2>
                        <motion.div whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}>
                            <Link to="/signup" className={styles.primaryBtn}>
                                Get Started Free
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" style={{ marginLeft: '8px' }}>
                                    <path d="M5 12H19M19 12L12 5M19 12L12 19" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                                </svg>
                            </Link>
                        </motion.div>
                    </motion.div>
                </section>
            </main>
            <Footer />
        </div>
    );
};

export default GlossaryPage;
